
# html lang
language: zh-Hans

# main menu navigation
menu:
  主页: /
  文章:
      类别: /categories
      归档: /archives
      标签: /tags
  文件: /paper
  项目: /project
  动态: /activity
  搜索: /search
  # about: http://www.fooying.com
  # rss: /atom.xml

# Miscelaneous
favicon: mylogo.png
logo: mylogo.png

share:
    show: false
    img:
    img_alt:
    tip_text: test

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# baidu url js push
baidu_url_js_push: true


# comment extend, support gialk
comment_extend:
    gitalk:
        enable: true
        owner: Boringboys
        repo: boringboys.github.io
        admin: Boringboys
        clientID: 198263188d4839476f77
        clientSecret: 191b4db05dddbd27c73bb8d793cbfa6baa9b416e

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

#footer
index_page: http://www.boringboys.top
main_site: http://www.boringboys.top
github: https://github.com/boringboys
links_url: /links

# 友情链接
links:
  cshsonice的技术分享博客: https://xchens.cn/
  湖畔的小亭子: http://blog.leepanda.top/

# project
projects:
  My-Blog:
    url: https://github.com/Boringboys/boringboys.github.io
    descript: a github pages

# activitys
activitys:
  暂时没有活动:
    date: 0000-00-00
    url: /
    type: 无

# papers
papers:
    什么都没有: /
    
# Local search
## 
## 
local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
