name: Build and Deploy my gitpages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out
        uses: actions/checkout@v2
        
      - name: Set-node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      
      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install git -y
      
      - name: Install Hexo
        run: |
          npm install -g hexo-cli
      
      - name: Build
        run: |
          npm install
          hexo generate
      
      - name: Deploy
        env: 
          REPO: github.com/Boringboys/boringboys.github.io
        run: |
          cd ./public
          git init
          git config user.name boringboys
          git config user.email boringboys@email.auwave
          git add .
          git commit -m "Auto deploy gitpages at $(data + '%Y-%m-%d %H:%M:%S %s')"
          git push --force --quiet "https://${{ secrets.MY_ACCESS_TOKEN }}@$REPO" master:pages
